project:
  type: website
  output-dir: docs

website:
  title: "Introduction to Statistical Learning"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: github
        href: https://github.com/aspteaching/Intro2StatisticalLearning
        aria-label: "GitHub Repository"
  sidebar:
    style: "docked"
    contents:
      - section: "Introduction"
        contents:
          - href: index.qmd
            text: Home
          - href: C0-Intro2StatLearn-PD_AS.qmd
            text: Course presentation
          - href: C1.1-SupervisedLearning-PD_AS.qmd
            text: Supervised Learning
          - href: C1.2-Model_validation_and_Resampling.qmd
            text: Validation and Resampling
          - href: Lab-C1.1-knn.Rmd
            text: Lab-C1.1-KNN

      - section: "Tree-based Methods"
        contents:
          - href: C2.1-DecisionTrees-Slides-RevealJS.qmd
            text: Decision Trees
          - href: labs/Lab-C2.1-Trees-guided-classification-regression_reduced.Rmd
            text: Lab-C2.1-CART (R)
          - href: labs/Lab-C2.1-Trees-guided-classification-regression_reduced_python.ipynb
            text: Lab-C2.1-CART (Python)

      - section: "Ensemble Methods"
        contents:
          - href: C2.2-Ensemble_Methods-Slides.qmd
            text: Ensemble Methods
          - href: labs/Lab-C2.3-Random_Forests.qmd
            text: Lab-C2.3-Random Forest
          - href: labs/Lab-C2.4-Boosting.qmd
            text: Lab-C2.4-Boosting
          - href: labs/Lab-C2.5-The-caret_package.qmd
            text: Lab-C2.5-Caret

      - section: "Neural Networks"
        contents:
          - href: C3.1-Introduction_to_ANN-Slides.qmd
            text: Neural Networks
          - href: C3.1b-Introduction_to_Keras_and_Scikit-Learn-Slides.qmd
            text: Keras and Scikit-Learn
          - href: labs/Lab-C3.1b-IrisANN-Modular.ipynb
            text: Lab-C3.1a-Species Classification with ANN Lab (Python)
          - href: labs/Lab-C3.1b-IrisANN-Training-ScikitLearn.ipynb
            text: Lab-C3.1b-Species Classification with ANN using Scikit-Learn
          - href: labs/Lab-C3.1b-IrisANN-Training-Keras.ipynb
            text: Lab-C3.1c-Species Classification with ANN using Keras
          - href: labs/Lab-C3.2-DividendPrediction_ANN.qmd
            text: Lab-C3.2-Dividend Prediction with ANN (R)
            
      - section: "Deep Learning"
        contents:
          - href: C3.2-Introduction_to_Deep_Learning-Slides.qmd
            text: Deep Learning
          - href: C3.3-Convolutional_Neural_Networks-Slides.qmd
            text: Convolutional Neural Networks
          - href: labs/Lab_C3_3_Introduction_to_Keras_and_CNNs.ipynb
            text: Lab-C3.3-Image-Classification-with-CNN 

      - section: "Resources"
        contents:  
           - href: Ressources.qmd
             text: References and Ressources
             
# 
# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
    # link-external-newwindow: true  #Enlaces externos se abren en nueva pestaña
