<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.47">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>c2.1-decisiontrees-slides-body – Introduction to Statistical Learning</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar docked nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Introduction to Statistical Learning</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/aspteaching/Intro2StatisticalLearning"> <i class="bi bi-github" role="img" aria-label="GitHub Repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Introduction</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C0-Intro2StatLearn-PD_AS.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Course presentation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C1.1-SupervisedLearning-PD_AS.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Supervised Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C1.2-Model_validation_and_Resampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Validation and Resampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Lab-C1.1-knn.Rmd" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C1.1-KNN</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Tree-based Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C2.1-DecisionTrees-Slides-RevealJS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Decision Trees</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C2.1-Trees-guided-classification-regression_reduced.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C2.1-CART (R)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C2.1-Trees-guided-classification-regression_reduced_python.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C2.1-CART (Python)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Ensemble Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C2.2-Ensemble_Methods-Slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ensemble Methods</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C2.3-Random_Forests.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C2.3-Random Forest</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C2.4-Boosting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C2.4-Boosting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C2.5-The-caret_package.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C2.5-Caret</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Neural Networks</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C3.1-Introduction_to_ANN-Slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C3.1b-Introduction_to_Keras_and_Scikit-Learn-Slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Keras and Scikit-Learn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C3.1b-IrisANN-Modular.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C3.1a-Species Classification with ANN Lab (Python)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C3.1b-IrisANN-Training-ScikitLearn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C3.1b-Species Classification with ANN using Scikit-Learn</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C3.1b-IrisANN-Training-Keras.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C3.1c-Species Classification with ANN using Keras</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab-C3.2-DividendPrediction_ANN.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C3.2-Dividend Prediction with ANN (R)</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C3.2-Introduction_to_Deep_Learning-Slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./C3.3-Convolutional_Neural_Networks-Slides.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Convolutional Neural Networks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labs/Lab_C3_3_Introduction_to_Keras_and_CNNs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab-C3.3-Image-Classification-with-CNN</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">Resources</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Ressources.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References and Ressources</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="outline" class="level2" data-visibility="hidden">
<h2 data-visibility="hidden" class="anchored" data-anchor-id="outline">Outline</h2>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: mlbench</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'mlbench' was built under R version 4.4.3</code></pre>
</div>
</div>
<ol type="1">
<li>Introduction to decision trees</li>
<li>Data cleaning and preprocessing</li>
<li>Pruning and optimization</li>
<li>Classification trees</li>
<li>Regression trees</li>
<li>Ensemble methods and advanced topics</li>
<li>Practical examples and exercises</li>
<li>Conclusion and future directions</li>
</ol>
</section>
<section id="introduction-to-decision-trees" class="level1">
<h1>Introduction to Decision Trees</h1>
<section id="motivation" class="level2">
<h2 class="anchored" data-anchor-id="motivation">Motivation</h2>
<ul>
<li>In many real-world applications, decisions need to be made based on complex, multi-dimensional data.</li>
<li>One goal of statistical analysis is to provide insights and guidance to support these decisions.</li>
<li>Decision trees provide a way to organize and summarize information in a way that is easy to understand and use in decision-making.</li>
</ul>
</section>
<section id="examples" class="level2">
<h2 class="anchored" data-anchor-id="examples">Examples</h2>
<ul>
<li><p>A bank needs to have a way to decide if/when a customer can be granted a loan.</p></li>
<li><p>A doctor may need to decide if a patient has to undergo a surgery or a less aggressive treatment.</p></li>
<li><p>A company may need to decide about investing in new technologies or stay with the traditional ones.</p></li>
</ul>
<p>In all those cases a decision tree may provide:</p>
<ul>
<li>A <em>structured approach to decision-making</em>,</li>
<li><strong>Based on data</strong></li>
<li>That can be <strong>be easily explained and justified</strong>.</li>
</ul>
</section>
<section id="an-intuitive-approach" class="level2">
<h2 class="anchored" data-anchor-id="an-intuitive-approach">An intuitive approach</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>Decisions are often based on asking a sequence of yes/no questions -from more general to more specific- based on available information, whose answers induce binary splits on data that end up with some grouping or classification.</p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/decTree4HypertensionNew.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/decTree4HypertensionNew.png" class="img-fluid figure-img" style="width:80.0%"></p>
<figcaption>A doctor may classify patients at high or low cardiovascular risk using some type of decision tree</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<p>This process can be more generically stated in the context of supervised learning.</p>
</section>
<section id="the-prediction-problem." class="level2">
<h2 class="anchored" data-anchor-id="the-prediction-problem.">The Prediction Problem.</h2>
<ul>
<li><p>Let <span class="math inline">\((X, Y)\)</span> be a r.v. with support <span class="math inline">\(\mathcal{X} \times \mathcal{Y} \subseteq \mathbb{R}^{p} \times \mathbb{R}\)</span>.</p></li>
<li><p>General supervised learning or prediction problem:</p>
<ul>
<li><p>Training sample: <span class="math inline">\(S=\left\{\left(\boldsymbol{x}_{1}, y_{1}\right), \ldots,\left(\boldsymbol{x}_{n}, y_{n}\right)\right\}\)</span>, i.i.d. from <span class="math inline">\((\boldsymbol{X}, Y)\)</span>.</p></li>
<li><p>The goal is to define a function (possibly depending on the sample) <span class="math inline">\(h_{S}: \mathcal{X} \mapsto \mathcal{Y}\)</span> such that for a new independent observation <span class="math inline">\((\boldsymbol{x}_{n+1}, y_{n+1})\)</span> , from which we only know <span class="math inline">\(\boldsymbol{x}_{n+1}\)</span>, it happens that: <span class="math display">\[
\hat{y}_{n+1}=h_{S}\left(x_{n+1}\right) \text { is close to } y_{n+1} \text { (in some sense). }
\]</span></p></li>
</ul></li>
<li><p>Function <span class="math inline">\(h_{S}\)</span> is generically called a <em>prediction function</em>, or depending on the case, <em>classification</em> or <em>regression</em> function.</p></li>
</ul>
</section>
<section id="classification-and-regression" class="level2">
<h2 class="anchored" data-anchor-id="classification-and-regression">Classification and Regression</h2>
<p>The prediction function <span class="math inline">\(h_{S}\)</span> is said to describe a <em>classification</em> or a <em>regression</em> problem depending on the case.</p>
<ul>
<li><p>If <span class="math inline">\(\mathcal{Y} \subseteq \mathbb{R}\)</span> (or <span class="math inline">\(\mathcal{Y}\)</span> an interval) we have a standard <em>regression problem</em>.</p>
<ul>
<li>Example: <em>Relating Salary and demographic variables</em></li>
</ul></li>
<li><p>If <span class="math inline">\(\mathcal{Y}=\{0,1\}\)</span> (or, also, <span class="math inline">\(\mathcal{Y}=\{-1,1\}\)</span> ) we have a problem of <em>binary classification</em> or discrimination.</p>
<ul>
<li>Example: <em>Predicting if a “cured” disease will recidive (re-appear)</em></li>
</ul></li>
<li><p>If <span class="math inline">\(\mathcal{Y}=\{1, \ldots, K\}\)</span> (or <span class="math inline">\(\left.\mathcal{Y}=\left\{\boldsymbol{y} \in\{0,1\}^{K}: \sum_{k=1}^{K} y_{k}=1\right\}\right)\)</span> we face a of <span class="math inline">\(K\)</span> classes classification problem.</p>
<ul>
<li>Example: <em>Classifying a tumor into one of many types</em></li>
</ul></li>
</ul>
</section>
<section id="supervised-learning-1" class="level2">
<h2 class="anchored" data-anchor-id="supervised-learning-1">Supervised learning (1)</h2>
<ul>
<li><p>Probabilistic model for supervised learning</p>
<ul>
<li><p>Response variable <span class="math inline">\(Y\)</span>.</p></li>
<li><p>Explanatory variables (features) <span class="math inline">\(\boldsymbol{X}=\left(X_{1}, \ldots, X_{p}\right)\)</span>.</p></li>
<li><p>Data <span class="math inline">\(\left(\boldsymbol{x}_{i}=\left(x_{i 1}, \ldots, x_{i p}\right), y_{i}\right), i=1, \ldots, n\)</span> i.i.d. from the random variable <span class="math display">\[
\left(\boldsymbol{X}=\left(X_{1}, \ldots, X_{p}\right), Y\right) \sim \operatorname{Pr}(\boldsymbol{X}, Y)
\]</span></p></li>
</ul></li>
<li><p><span class="math inline">\(\operatorname{Pr}(\boldsymbol{X}, \boldsymbol{Y})\)</span> denotes the joint distribution of <span class="math inline">\(\boldsymbol{X}\)</span> and <span class="math inline">\(Y\)</span>.</p></li>
</ul>
<!--     -   When this joint distribution is continuous, -->
<!--         $\operatorname{Pr}(\boldsymbol{X}, Y)$ is the joint probability -->
<!--         density function. -->
<!-- ------------------------------------------------------------------------ -->
<ul>
<li>Main interest is <em>predicting</em> <span class="math inline">\(Y\)</span> from <span class="math inline">\(\boldsymbol{X}\)</span>.</li>
</ul>
</section>
<section id="supervised-learning-2" class="level2">
<h2 class="anchored" data-anchor-id="supervised-learning-2">Supervised learning (2)</h2>
<ul>
<li><p>Given the probabilistic model it can be re-stated as <em>learning the conditional distribution</em> <span class="math inline">\(\operatorname{Pr}(Y \mid \boldsymbol{X})\)</span>.</p></li>
<li><p>In practice we focus on <em>learning a conditional location parameter</em>: <span class="math display">\[
\mu(\boldsymbol{x})=\underset{\mu}{\operatorname{argmin}} \mathbb{E}(L(Y, \mu) \mid \boldsymbol{X}=\boldsymbol{x}),
\]</span> where <span class="math inline">\(L(y, \hat{y})\)</span>, loss function, measures the error of predicting <span class="math inline">\(y\)</span> with <span class="math inline">\(\hat{y}\)</span>.</p></li>
<li><p>For quadratic loss, <span class="math inline">\(L(y, \hat{y})=(y-\hat{y})^{2}, \mu(x)\)</span> is the regression function: <span class="math display">\[
\mu(\boldsymbol{x})=\mathbb{E}(Y \mid \boldsymbol{X}=\boldsymbol{x})
\]</span></p></li>
</ul>
</section>
<section id="introducing-decision-trees" class="level2">
<h2 class="anchored" data-anchor-id="introducing-decision-trees">Introducing decision trees</h2>
<ul>
<li><p>A decision tree is a graphical representation of a series of decisions and their potential outcomes.</p></li>
<li><p>It is obtained by recursively <em>stratifying</em> or <em>segmenting</em> the <em>feature space</em> into a number of simple regions.</p></li>
<li><p>Each region (decision) corresponds to a <em>node</em> in the tree, and each potential outcome to a <em>branch</em>.</p></li>
<li><p>The tree structure can be used to guide decision-making based on data.</p></li>
</ul>
</section>
<section id="types-of-decision-trees" class="level2">
<h2 class="anchored" data-anchor-id="types-of-decision-trees">Types of decision trees</h2>
<ul>
<li><p>Decision trees are simple yet reliable predictors that can be use for both classification or prediction</p>
<ul>
<li><p><strong>Classification Trees</strong> are <em>classifiers</em>, used when the response variable is categorical</p></li>
<li><p><strong>Regression Trees</strong>, are <em>regression models</em> used to predict the values of a numerical response variable.</p></li>
</ul></li>
</ul>
</section>
<section id="trees-vs-decision-trees" class="level2">
<h2 class="anchored" data-anchor-id="trees-vs-decision-trees">Trees vs Decision Trees</h2>
<div class="columns">
<div class="column" style="width:50%;">
<div class="font80">
<ol type="1">
<li>A tree is a set of nodes and edges organized in a hierarchical fashion.<br> In contrast to a graph, in a tree there are no loops. <!-- Internal nodes are denoted with circles and terminal nodes with squares. --></li>
</ol>
<p><br></p>
<ol start="2" type="1">
<li>A decision tree is a tree where <em>each split node stores a boolean test function</em> to be applied to the incoming data. <br> Each leaf stores the final answer (predictor)</li>
</ol>
</div>
</div><div class="column" style="width:50%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/1.1-DecisionTrees-Slides_insertimage_1.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/1.1-DecisionTrees-Slides_insertimage_1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:45.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/1.1-DecisionTrees-Slides_insertimage_2.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/1.1-DecisionTrees-Slides_insertimage_2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:45.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="notation-used-in-trees-1" class="level2">
<h2 class="anchored" data-anchor-id="notation-used-in-trees-1">Notation used in trees (1)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/clipboard-58173806.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-58173806.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="notation-used-in-trees-2" class="level2">
<h2 class="anchored" data-anchor-id="notation-used-in-trees-2">Notation used in trees (2)</h2>
<ul>
<li><p>A node is denoted by <span class="math inline">\(t\)</span>.</p></li>
<li><p>The left and right child nodes are denoted by <span class="math inline">\(t_{L}\)</span> and <span class="math inline">\(t_{R}\)</span></p></li>
<li><p>The collection of all nodes in the tree is denoted <span class="math inline">\(T\)</span></p></li>
<li><p>The collection of all the leaf nodes is denoted <span class="math inline">\(\tilde{T}\)</span></p></li>
<li><p>A split will be denoted by <span class="math inline">\(s\)</span>.</p></li>
<li><p>The set of all splits is denoted by <span class="math inline">\(S\)</span>.</p></li>
</ul>
<!-- ## A first look at pros and cons   (CREC QUE NO CAL)(-->
<!-- -   Trees provide an simple approach to classification and prediction for both categorical or numerical outcomes. -->
<!-- -   The results are intuitive and easy to explain and interpret. -->
<!-- -   They are, however, not very accurate, but -->
<!-- -   Aggregation of multiple trees built on the same data can result on dramatic improvements in prediction accuracy, at the expense of some loss of interpretation. -->
<!-- ## What do we need to learn? -->
<!-- -   We need **context**:  -->
<!--     -   When is it appropriate to rely on decision trees? -->
<!--     -   When would other approaches be preferable? -->
<!--     -   What type of decision trees can be used? -->
<!-- -   We need to know how to **build good trees** -->
<!--     -   How do we *construct* a tree? -->
<!--     -   How do we *optimize* the tree? -->
<!--     -   How do we *evaluate* it? -->
<!-- ## More about context -->
<!-- -   Decision trees are non parametric, data guided predictors, well suited in many situations such as: -->
<!--     -   Non-linear relationships. -->
<!--     -   High-dimensional data. -->
<!--     -   Interaction between variables exist. -->
<!--     -   Mixed data types. -->
<!-- -   They are not so appropriate for complex datasets, or complex problems, that require expert knowledge. -->
<!-- - [See here some examples of each situation!](https://g.co/gemini/share/781b7d88e03a) -->
</section>
<section id="tree-based-models-in-practice" class="level2">
<h2 class="anchored" data-anchor-id="tree-based-models-in-practice">Tree-based models in practice</h2>
<div class="font80">
<table class="caption-top table">
<colgroup>
<col style="width: 26%">
<col style="width: 33%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Package</th>
<th>Language</th>
<th>Role</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>rpart</code></td>
<td>R</td>
<td>CART implementation</td>
<td>Standard tree fitting</td>
</tr>
<tr class="even">
<td><code>tree</code></td>
<td>R</td>
<td>CART (simplified)</td>
<td>Mainly for teaching</td>
</tr>
<tr class="odd">
<td><code>caret</code></td>
<td>R</td>
<td>Modeling framework</td>
<td>Unified interface</td>
</tr>
<tr class="even">
<td><code>scikit-learn</code></td>
<td>Python</td>
<td>CART-like trees</td>
<td>Standard in Python ecosystem</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>Most implementations are based on <strong>CART</strong></li>
<li>Focus on <strong>model fitting and prediction</strong></li>
<li>Details of construction will be studied next</li>
</ul>
</section>
</section>
<section id="building-classification-trees" class="level1">
<h1>Building Classification Trees</h1>
<section id="building-the-trees" class="level2">
<h2 class="anchored" data-anchor-id="building-the-trees">Building the trees</h2>
<ul>
<li><p>As with any model, we aim not only at construting trees.</p></li>
<li><p>We wish to build good trees and, if possible, optimal trees in some sense we decide.</p></li>
<li><p>In order to <strong>build good trees</strong> we must decide</p>
<ul>
<li><p>How to <em>construct</em> a tree?</p></li>
<li><p>How to <em>optimize</em> the tree?</p></li>
<li><p>How to <em>evaluate</em> it?</p></li>
</ul></li>
</ul>
</section>
<section id="building-a-tree" class="level2">
<h2 class="anchored" data-anchor-id="building-a-tree">Building a tree</h2>
<ul>
<li><p>A binary decision tree is built by defining a series of (recursive) splits on the feature space.</p></li>
<li><p>The splits are decided in such a way that the associated learning task is attained</p>
<ul>
<li>by setting thresholds on the variables values,</li>
<li>that induce paths in the tree,</li>
</ul></li>
<li><p>The ultimate goal of the tree is to be able to use a combination of the splits to accomplish the learning task with as small an error as possible.</p></li>
</ul>
</section>
<section id="trees-partition-the-space" class="level2">
<h2 class="anchored" data-anchor-id="trees-partition-the-space">Trees partition the space</h2>
<ul>
<li><p><em>A tree represents a recursive splitting of the space</em>.</p>
<ul>
<li>Every node of interest corresponds to one region in the original space.</li>
<li>Two child nodes occupy two different regions.</li>
<li>Together, they yield same region as that of the parent node.</li>
</ul></li>
<li><p>In the end, every leaf node is assigned with a class (or value) and a test point is assigned with the class (or value) of the leaf node it lands in.</p></li>
</ul>
</section>
<section id="the-tree-represents-the-splitting" class="level2">
<h2 class="anchored" data-anchor-id="the-tree-represents-the-splitting">The tree represents the splitting</h2>
<div class="r-stack">
<div class="fragment fade-in absolute" data-top="100" data-left="150">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/splits_nodes_1.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/splits_nodes_1.png" class="quarto-figure quarto-figure-center figure-img" width="800" height="400"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment fade-in absolute" data-top="100" data-left="150">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/splits_nodes_2.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/splits_nodes_2.png" class="quarto-figure quarto-figure-center figure-img" width="800" height="400"></p>
</figure>
</div>
</div>
</div>
</div>
<div class="fragment fade-in absolute" data-top="100" data-left="150">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/splits_nodes_3.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/splits_nodes_3.png" class="quarto-figure quarto-figure-center figure-img" width="800" height="400"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
<!-- -   [Animation](https://youtu.be/1ow2tF9Ezgs) -->
</section>
<section id="different-splits-are-possible" class="level2">
<h2 class="anchored" data-anchor-id="different-splits-are-possible">Different splits are possible</h2>
<ul>
<li>It is always possible to split a space in distinct ways</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/1.1-DecisionTrees-Slides_insertimage_3.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/1.1-DecisionTrees-Slides_insertimage_3.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="400"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Some ways perform better than other for a given task, but rarely will they be perfect.</p></li>
<li><p>So we aim at combining splits to find a better rule.</p></li>
</ul>
</section>
<section id="building-a-decision-tree" class="level2">
<h2 class="anchored" data-anchor-id="building-a-decision-tree">Building a decision tree</h2>
<p>Tree building involves the following three elements:</p>
<ol type="1">
<li>The selection of the splits, i.e., how do we decide which node (region) to split and how to split it?</li>
</ol>
<ul>
<li>How to select from the pool of candidate splits?</li>
<li>What are appropriate <em>goodness of split</em> criteria?</li>
<li>When to declare a node terminal and <em>stop splitting</em>?</li>
</ul>
<ol start="2" type="1">
<li><p>How to assign each terminal node to a class</p></li>
<li><p>How to ensure the tree is the <em>best possible</em> we can build.</p></li>
</ol>
</section>
<section id="tree-construction-algorithm-cart" class="level2">
<h2 class="anchored" data-anchor-id="tree-construction-algorithm-cart">Tree construction algorithm (CART)</h2>
<p>The most popular algorithm for buildiong trees is CART which can be schemeatically described as follows:</p>
<ol type="1">
<li><p>Initialize: all data in root node</p></li>
<li><p>Repeat for each node, until stopping criterion is met</p></li>
</ol>
<p>2.1 Generate candidate splits</p>
<p>2.2 Select best split (maximize impurity reduction)</p>
<p>2.3 Split node into two children</p>
<p>CART is a greedy recursive partitioning algorithm.</p>
</section>
<section id="tb-1.1---split-selection" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.1---split-selection">TB 1.1 - Split selection</h2>
<div class="font80">
<ul>
<li><p>To build a Tree, questions have to be generated that induce splits based on the value of a single variable.</p></li>
<li><p>Ordered variable <span class="math inline">\(X_j\)</span>:</p>
<ul>
<li>Is <span class="math inline">\(X_j \leq c\)</span>? for all possible thresholds <span class="math inline">\(c\)</span>.</li>
<li>Split lines: parallel to the coordinates.</li>
</ul></li>
<li><p>Categorical variables, <span class="math inline">\(X_j \in \{1, 2, \ldots, M\}\)</span>:</p>
<ul>
<li>Is <span class="math inline">\(X_j \in A\)</span>?, where <span class="math inline">\(A \subseteq M\)</span> .</li>
</ul></li>
<li><p>The pool of <em>candidate splits</em> for all <span class="math inline">\(p\)</span> variables is formed by combining all the generated questions.</p></li>
<li><p>With the pool of candidate splits, next step is to decide <em>which one to use</em> when constructing the decision tree.</p></li>
</ul>
</div>
</section>
<section id="tb-1.2.1---goodness-of-split" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.1---goodness-of-split">TB 1.2.1 - Goodness of Split</h2>
<ul>
<li><p>Intuitively, when we split the points we want the region corresponding to each leaf node to be “pure”.</p></li>
<li><p>That is, we aim at regions where most points belong to the same class.</p></li>
<li><p>With this goal in mind we select splits by measuring their “goodness of split” using some of the available <em>Impurity fuctions</em> introduced later.</p></li>
</ul>
</section>
<section id="tb-1.2.2---measuring-homogeneity" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.2---measuring-homogeneity">TB 1.2.2 - Measuring homogeneity</h2>
<ul>
<li><p>In order to measure homogeneity,or as called here, <em>purity</em>, of splits we rely on different <em>Impurity functions</em></p></li>
<li><p>These functions allow us to quantify the extent of <em>homogeneity</em> for a region containing data points from possibly different classes.</p>
<ul>
<li><p>A region will be more pure or more homogeneous the less variable is the set of points it contains.</p></li>
<li><p>In the next image regions on the right of the image are homogeneous that is <em>purer</em> than the heterogeneous regions on the left.</p></li>
</ul></li>
</ul>
</section>
<section id="tb-1.2.3---good-splits-vs-bad-splits" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.3---good-splits-vs-bad-splits">TB 1.2.3 - Good splits vs bad splits</h2>
<div class="columns">
<div class="fragment">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/BadSplit.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/BadSplit.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p><em>Purity</em> not increased</p>
</div>
</div><div class="fragment">
<div class="column" style="width:50%;">
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/GoodSplit.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/GoodSplit.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
<p><em>Purity</em> increased</p>
</div>
</div>
</div>
</section>
<section id="tb-1.2.4---impurity-functions" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.4---impurity-functions">TB 1.2.4 - Impurity functions</h2>
<div class="font70">
<p>An <strong>impurity function</strong> is a function <span class="math inline">\(\Phi\)</span> defined on the set of all <span class="math inline">\(K\)</span>-tuples of numbers <span class="math inline">\(\mathbf{p}= \left(p_{1}, \cdots, p_{K}\right)\)</span> s.t. <span class="math inline">\(p_{j} \geq 0, \,  \sum_{j=1}^K p_{j}=1\)</span>, <span class="math display">\[
\Phi: \left(p_{1}, \cdots, p_{K}\right) \rightarrow [0,1]
\]</span></p>
<p>with the properties:</p>
<ol type="1">
<li><span class="math inline">\(\Phi\)</span> is maximum only for the uniform distribution, that is all the <span class="math inline">\(p_{j}\)</span> are equal.</li>
<li><span class="math inline">\(\Phi\)</span> is minimum only at points <span class="math inline">\((1,0, \ldots, 0)\)</span>,<span class="math inline">\((0,1,0, \ldots, 0)\)</span>, <span class="math inline">\(\ldots,(0,0, \ldots, 0,1)\)</span>, i.e., when the probability of being in a certain class is 1 and 0 for all the other classes.</li>
<li><span class="math inline">\(\Phi\)</span> is a symmetric function of <span class="math inline">\(p_{1}, \cdots, p_{K}\)</span>, i.e., if we permute <span class="math inline">\(p_{j}\)</span>, <span class="math inline">\(\Phi\)</span> remains constant.</li>
</ol>
</div>
</section>
<section id="tb-1.2.5---some-impurity-functions" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.5---some-impurity-functions">TB 1.2.5 - Some Impurity Functions</h2>
<p>The functions below are commonly used to measure impurity.</p>
<!-- - Let $t$ be a node and $p(k|t)$ the conditional probability of observing class $k$ at that node. The node information function $i(t)$ may be defined as: -->
<div class="font80">
<ul>
<li><p><strong>Entropy</strong>: <span class="math inline">\(\Phi_E (\mathbf{p}) = -\sum_{j=1}^K p_j\log (p_j)\)</span> .</p></li>
<li><p><strong>Gini Index</strong>: <span class="math inline">\(\Phi_G (\mathbf{p}) = 1-\sum_{j=1}^K p_j^2\)</span>.</p></li>
<li><p><strong>Misclassification rate</strong>: <span class="math inline">\(\Phi_M (\mathbf{p}) = \sum_{i=1}^K p_j(1-p_j)\)</span>.</p></li>
</ul>
</div>
<ul>
<li>In practice, only the first two are recommended because misclassification rate is not sensitive enough to differences in class probabilies.</li>
</ul>
</section>
<section id="tb-1.2.5-impurity-functions-behavior" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.5-impurity-functions-behavior">TB 1.2.5 Impurity functions behavior</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/impurity.jpg"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/impurity.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:66.0%"></p>
</figure>
</div>
</div>
</div>
<div class="small">
<ul>
<li>Red curve: Entropy function (rescaled),</li>
<li>Green curve: Gini index</li>
<li>Blue curve: Resubstitution estimate of the misclassification rate.</li>
</ul>
</div>
</section>
<section id="tb-1.2.6---impurity-measure-of-a-split" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.6---impurity-measure-of-a-split">TB 1.2.6 - Impurity measure of a split</h2>
<ul>
<li>Given an impurity function <span class="math inline">\(\Phi\)</span>, a node <span class="math inline">\(t\)</span>, and given <span class="math inline">\(p(j \mid t)\)</span>, the estimated posterior probability of class <span class="math inline">\(j\)</span> given node <span class="math inline">\(t\)</span>, the <em>impurity measure of</em> <span class="math inline">\(t\)</span>, <span class="math inline">\(i(t)\)</span>, is:</li>
</ul>
<p><span class="math display">\[
i(t)=\phi\left (p(1 \mid t), p(2 \mid t), \ldots, p(K \mid t)\right)
\]</span></p>
<ul>
<li>That is, the <em>impurity measure</em> of a split (or a node) is the impurity function computed on probabilities associated (conditional) with a node.</li>
</ul>
</section>
<section id="tb-1.2.7---goodness-of-a-split" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.7---goodness-of-a-split">TB 1.2.7 - Goodness of a split</h2>
<ul>
<li>Once we have defined <span class="math inline">\(i(t)\)</span>, we define the goodness of split <span class="math inline">\(s\)</span> for node <span class="math inline">\(t\)</span>, denoted by <span class="math inline">\(\Phi(s, t)\)</span> :</li>
</ul>
<p><span class="math display">\[
\Phi(s, t)=\Delta i(s, t)=i(t)-p_{R} i\left(t_{R}\right)-p_{L} i\left(t_{L}\right)
\]</span></p>
<ul>
<li><p>The best split for the single variable <span class="math inline">\(X_{j}\)</span> is the one that has the largest value of <span class="math inline">\(\Phi(s, t)\)</span> over all <span class="math inline">\(s \in \mathcal{S}_{j}\)</span>, the set of possible distinct splits for <span class="math inline">\(X_{j}\)</span>.</p></li>
<li><p>We choose the split that maximizes impurity reduction, by using a <em>greedy strategy</em>: the best split is chosen locally at each step.</p></li>
</ul>
<!-- ## TB 1.2.8 - Impurity score for a node -->
<!-- -   The impurity, $i(t)$, of a node is based solely on the estimated -->
<!--     posterior probabilities of the classes -->
<!--     -   That is, *it doesn't account for the size of* $t$. -->
<!-- -   This is done by the *impurity score* of $t$, defined as -->
<!--     $I(t)=i(t)\cdot p(t)$, a *weighted impurity measure* of node $t$ -->
<!--     that takes into account: -->
<!--     -   The estimated posterior probabilities of the classes, -->
<!--     -   The estimated proportion of data that go to node $t$. -->
<!-- ## TB 1.2.9 - Applications of $I(t)$ -->
<!-- -   $I(t)$ can be used to: -->
<!--     -   Define the aggregated impurity of a tree, by adding the impurity -->
<!--         scores of all terminal leaves. -->
<!--     -   Provide a weighted measure of impurity decrease for a split: -->
<!--         $\Delta I(s, t)=p(t) \Delta i(s, t)$. -->
<!--     -   Define a criteria for stop splitting a tree (see below). -->
</section>
<section id="tb-1.2.8---entropy-as-an-impurity-measure" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.8---entropy-as-an-impurity-measure">TB 1.2.8 - Entropy as an impurity measure</h2>
<ul>
<li>The entropy of a node, <span class="math inline">\(t\)</span>, that is split in <span class="math inline">\(n\)</span> child nodes <span class="math inline">\(t_1\)</span>, <span class="math inline">\(t_2\)</span>, …, <span class="math inline">\(t_n\)</span>, is:</li>
</ul>
<p><span class="math display">\[
\Phi_E (\mathbf{p}) = H(\mathbf{t})=-\sum_{i=1}^{n} \underbrace{P\left(t_{i}\right)}_{p_i} \log _{2} P\left(t_{i}\right)
\]</span></p>
<ul>
<li><p>From here, an information gain (that is impurity decrease) measure can be introduced by comparing:</p></li>
<li><p>the entropy of the parent node before the split to</p></li>
<li><p>that of a weighted sum of the child nodes after the split where, - weights are proportional to the number of observations in each node.</p></li>
</ul>
</section>
<section id="tb-1.2.9---information-gain" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.2.9---information-gain">TB 1.2.9 - Information gain</h2>
<ul>
<li>For a split <span class="math inline">\(s\)</span> and a set of observations (a node) <span class="math inline">\(t\)</span>, information gain is defined as:</li>
</ul>
<p><span class="math display">\[
\begin{aligned}
&amp; IG(t, s)=\text { (original entr.) }-(\text { entr. after split) } \\
&amp; IG(t, s)=H(t)-\sum_{i=1}^{n} \frac{\left|t_{i}\right|}{t} H\left(x_{i}\right)
\end{aligned}
\]</span></p>
</section>
<section id="example-1-pears-vs-apples" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="example-1-pears-vs-apples">Example 1: Pears vs Apples</h2>
<div class="columns">
<div class="column" style="width:40%;">
<p>Consider the problem of designing an algorithm to automatically differentiate between apples and pears (class labels) given only their width and height measurements (features).</p>
</div><div class="column" style="width:60%;">
<div class="font80">
<table class="caption-top table">
<thead>
<tr class="header">
<th><strong>Width</strong></th>
<th><strong>Height</strong></th>
<th><strong>Fruit</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>7.1</td>
<td>7.3</td>
<td>Apple</td>
</tr>
<tr class="even">
<td>7.9</td>
<td>7.5</td>
<td>Apple</td>
</tr>
<tr class="odd">
<td>7.4</td>
<td>7.0</td>
<td>Apple</td>
</tr>
<tr class="even">
<td>8.2</td>
<td>7.3</td>
<td>Apple</td>
</tr>
<tr class="odd">
<td>7.6</td>
<td>6.9</td>
<td>Apple</td>
</tr>
<tr class="even">
<td>7.8</td>
<td>8.0</td>
<td>Apple</td>
</tr>
<tr class="odd">
<td>7.0</td>
<td>7.5</td>
<td>Pear</td>
</tr>
<tr class="even">
<td>7.1</td>
<td>7.9</td>
<td>Pear</td>
</tr>
<tr class="odd">
<td>6.8</td>
<td>8.0</td>
<td>Pear</td>
</tr>
<tr class="even">
<td>6.6</td>
<td>7.7</td>
<td>Pear</td>
</tr>
<tr class="odd">
<td>7.3</td>
<td>8.2</td>
<td>Pear</td>
</tr>
<tr class="even">
<td>7.2</td>
<td>7.9</td>
<td>Pear</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</section>
<section id="example-1.-entropy-calculation" class="level2">
<h2 class="anchored" data-anchor-id="example-1.-entropy-calculation">Example 1. Entropy Calculation</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Example2-EntropyCalculation.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/Example2-EntropyCalculation.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="example-1.-information-gain" class="level2">
<h2 class="anchored" data-anchor-id="example-1.-information-gain">Example 1. Information Gain</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/Example2-IGCalculation.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="images/Example2-IGCalculation.png" class="img-fluid figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="tb.-1.3-overfitting-in-trees" class="level2">
<h2 class="anchored" data-anchor-id="tb.-1.3-overfitting-in-trees">TB. 1.3 Overfitting in trees</h2>
<p>As trees grow deeper:</p>
<ul>
<li>They fit the training data increasingly well and</li>
<li>Regions become smaller and more specific</li>
</ul>
<p>However, small regions may contain few observations causing predictions to become unstable and sensitive to noise</p>
<p>This results in_</p>
<ul>
<li>Low training error</li>
<li>Poor generalization to new data</li>
</ul>
<p>Altogether yields an idea: <em>It is probably better to not let the tree grow as much as it can but control its size</em>.</p>
</section>
<section id="tb.-1.3.1---when-to-stop-growing" class="level2">
<h2 class="anchored" data-anchor-id="tb.-1.3.1---when-to-stop-growing">TB. 1.3.1 - When to stop growing</h2>
<ul>
<li><p>Maximizing information gain is one possible criteria to choose among splits.</p></li>
<li><p>In order to avoid excessive complexity it is usually decided to stop splitting when <em>information gain does not compensate for increase in complexity</em>.</p></li>
</ul>
</section>
<section id="tb-1.3.2-stop-splitting-criteria" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.3.2-stop-splitting-criteria">TB 1.3.2 Stop splitting criteria</h2>
<ul>
<li>In practice, stop splitting is decided when: <span class="math display">\[
\max _{s \in S} \Delta I(s, t)&lt;\beta,
\]</span>where:
<ul>
<li><span class="math inline">\(\Delta I\)</span> represents the information gain associated with an optimal split <span class="math inline">\(s\)</span> and a node <span class="math inline">\(t\)</span>,</li>
<li>and <span class="math inline">\(\beta\)</span> is a pre-determined threshold.</li>
</ul></li>
</ul>
</section>
<section id="tb-1.-summary" class="level2">
<h2 class="anchored" data-anchor-id="tb-1.-summary">TB 1. Summary</h2>
<div class="font80">
<ul>
<li><p>Decision trees are built by iteratively partitioning data into smaller regions based on feature values.</p></li>
<li><p>Splits are aimed at producing purer nodes, that contains mostly data from one class.</p></li>
<li><p>Homogeneity is measured by impurity functions such as <em>Entropy</em>, <em>Gini Index</em> or <em>Misclassification rate</em></p></li>
<li><p>The best split is chosen from candidate splits as the one that maximizes impurity reduction for example through <em>Information Gain</em></p></li>
<li><p>Tree growth continues until impurity reduction is minimal, or a predefined depth or node size threshold is reached.</p></li>
</ul>
</div>
</section>
<section id="example-2.-the-pima-database" class="level2">
<h2 class="anchored" data-anchor-id="example-2.-the-pima-database">Example 2. The PIMA database</h2>
<ul>
<li>The Pima Indian Diabetes dataset contains 768 individuals (female) and 9 clinical variables.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">"PimaIndiansDiabetes2"</span>, <span class="at">package =</span> <span class="st">"mlbench"</span>)</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(PimaIndiansDiabetes2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 768
Columns: 9
$ pregnant &lt;dbl&gt; 6, 1, 8, 1, 0, 5, 3, 10, 2, 8, 4, 10, 10, 1, 5, 7, 0, 7, 1, 1…
$ glucose  &lt;dbl&gt; 148, 85, 183, 89, 137, 116, 78, 115, 197, 125, 110, 168, 139,…
$ pressure &lt;dbl&gt; 72, 66, 64, 66, 40, 74, 50, NA, 70, 96, 92, 74, 80, 60, 72, N…
$ triceps  &lt;dbl&gt; 35, 29, NA, 23, 35, NA, 32, NA, 45, NA, NA, NA, NA, 23, 19, N…
$ insulin  &lt;dbl&gt; NA, NA, NA, 94, 168, NA, 88, NA, 543, NA, NA, NA, NA, 846, 17…
$ mass     &lt;dbl&gt; 33.6, 26.6, 23.3, 28.1, 43.1, 25.6, 31.0, 35.3, 30.5, NA, 37.…
$ pedigree &lt;dbl&gt; 0.627, 0.351, 0.672, 0.167, 2.288, 0.201, 0.248, 0.134, 0.158…
$ age      &lt;dbl&gt; 50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 30, 34, 57, 59, 51, 3…
$ diabetes &lt;fct&gt; pos, neg, pos, neg, pos, neg, pos, neg, pos, pos, neg, pos, n…</code></pre>
</div>
</div>
</section>
<section id="why-these-variables-medical-interlude-1" class="level2">
<h2 class="anchored" data-anchor-id="why-these-variables-medical-interlude-1">Why these variables? (medical interlude 1)</h2>
<ul>
<li><p>Diabetes is a metabolic disorder related to:</p>
<ul>
<li>Blood sugar regulation</li>
<li>Insulin function</li>
<li>Long-term physiological changes</li>
</ul></li>
<li><p>Some variables are known to be associated with diabetes risk:</p>
<ul>
<li>Glucose (blood sugar levels)</li>
<li>Insulin (hormone regulating glucose)</li>
<li>Body mass (obesity)</li>
<li>Age (risk increases over time)</li>
</ul></li>
<li><p>These variables provide indirect evidence of metabolic health</p></li>
</ul>
</section>
<section id="interpreting-key-predictors" class="level2">
<h2 class="anchored" data-anchor-id="interpreting-key-predictors">Interpreting key predictors</h2>
<ul>
<li><p><strong>Glucose</strong>: High values indicate impaired blood sugar control</p></li>
<li><p><strong>Insulin</strong>: Abnormal levels may reflect sugar is not being controlled (Insuline Resistance).</p></li>
<li><p><strong>BMI (mass)</strong>: Obesity is a major risk factor for diabetes</p></li>
<li><p><strong>Age</strong>: Risk increases with cumulative metabolic stress</p></li>
<li><p><strong>Blood pressure</strong>: Often associated with metabolic syndrome</p></li>
</ul>
<p>The model combines these signals to predict diabetes risk</p>
</section>
<section id="example-2.-looking-at-the-data" class="level2">
<h2 class="anchored" data-anchor-id="example-2.-looking-at-the-data">Example 2. Looking at the data</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'ggplot2' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tibble' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'readr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'purrr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'stringr' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'forcats' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'lubridate' was built under R version 4.4.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.0
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlbench)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(PimaIndiansDiabetes2)</span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>vars <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"glucose"</span>, <span class="st">"insulin"</span>, <span class="st">"mass"</span>, <span class="st">"pressure"</span>, <span class="st">"age"</span>)</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>PimaIndiansDiabetes2 <span class="sc">%&gt;%</span></span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">all_of</span>(vars), diabetes) <span class="sc">%&gt;%</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="sc">-</span>diabetes, <span class="at">names_to =</span> <span class="st">"variable"</span>, <span class="at">values_to =</span> <span class="st">"value"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> diabetes, <span class="at">y =</span> value)) <span class="sc">+</span></span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">outlier.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>variable, <span class="at">scales =</span> <span class="st">"free_y"</span>) <span class="sc">+</span></span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 425 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ex.-2.-building-a-classification-tree" class="level2">
<h2 class="anchored" data-anchor-id="ex.-2.-building-a-classification-tree">Ex. 2. Building a classification tree</h2>
<ul>
<li><p>We wish to predict the probability of individuals in being diabete-positive or negative.</p>
<ul>
<li>We start building a tree with all the variables</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>model1 <span class="ot">&lt;-</span> <span class="fu">rpart</span>(diabetes <span class="sc">~</span>., <span class="at">data =</span> PimaIndiansDiabetes2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<!-- ## Viewing the tree as text -->
<!-- ::: font40 -->
<!-- ```{r} -->
<!-- model1 -->
<!-- ``` -->
<!-- ::: -->
<!-- ::: small -->
<!-- -   This representation shows the variables and split values that have been selected by the algorithm. -->
<!-- -   It can be used to classify (new) individuals following the decisions (splits) from top to bottom. -->
<!-- ::: -->
</section>
<section id="ex.2.-plotting-the-tree-1" class="level2">
<h2 class="anchored" data-anchor-id="ex.2.-plotting-the-tree-1">Ex.2. Plotting the tree (1)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model1)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(model1, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">cex=</span><span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-16-1.png" style="height:10cm" width="672" class="figure-img"></p>
<figcaption>Even without domain expertise the model seems <em>reasonable</em></figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="ex.-2.-plotting-the-tree-nicer" class="level2">
<h2 class="anchored" data-anchor-id="ex.-2.-plotting-the-tree-nicer">Ex. 2. Plotting the tree (Nicer)</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">require</span>(rpart.plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Cargando paquete requerido: rpart.plot</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rpart.plot' was built under R version 4.4.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">rpart.plot</span>(model1, <span class="at">cex=</span>.<span class="dv">7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>The tree plotted with the <code>rpart.plot</code> package.</figcaption>
</figure>
</div>
</div>
</div>
<div class="small">
<p>Each node shows: (1) the predicted class (‘neg’ or ‘pos’), (2) the predicted probability, (3) the percentage of observations in the node.</p>
</div>
</section>
</section>
<section id="prediction-with-trees" class="level1">
<h1>Prediction with Trees</h1>
<section id="tb-2---class-assignment" class="level2">
<h2 class="anchored" data-anchor-id="tb-2---class-assignment">TB 2 - Class Assignment</h2>
<ul>
<li><p>A decision tree classifies new data points as follows.</p>
<ul>
<li><p>We let a data point pass down the tree and see which leaf node it lands in.</p></li>
<li><p>Each leaf node defines a region where all observations share the same class.</p></li>
<li><p>The class of the leaf node is assigned to the new data point: all the points that land in the same leaf node will be given the same class.</p></li>
</ul></li>
<li><p>Trees produce <em>piecewise constant</em> predictions.</p></li>
</ul>
</section>
<section id="tb-2.1---class-assignment-rules" class="level2">
<h2 class="anchored" data-anchor-id="tb-2.1---class-assignment-rules">TB 2.1 - Class Assignment Rules</h2>
<ul>
<li><p>A class assignment rule assigns a class <span class="math inline">\(j=1, \cdots, K\)</span> to every terminal (leaf) node <span class="math inline">\(t \in \tilde{T}\)</span>.</p></li>
<li><p>The class assigned to node <span class="math inline">\(t\)</span> is denoted by <span class="math inline">\(\kappa(t)\)</span>,</p>
<ul>
<li>E.g., if <span class="math inline">\(\kappa(t)=2\)</span>, all points in node <span class="math inline">\(t\)</span> aree assigned to class 2.</li>
</ul></li>
<li><p>Within each node, we estimate class probabilities from the data.</p></li>
<li><p>If we use 0-1 loss, the class assignment rule picks the class with maximum posterior probability: <span class="math display">\[
\kappa(t)=\arg \max _{j} p(j \mid t)
\]</span></p></li>
<li><p>This rule corresponds to minimizing the 0–1 loss within each node.</p></li>
</ul>
</section>
<section id="tb-2.2.-estimating-the-error-rate-1" class="level2">
<h2 class="anchored" data-anchor-id="tb-2.2.-estimating-the-error-rate-1">TB 2.2. Estimating the error rate (1)</h2>
<ul>
<li><p>Let’s assume we have built a tree and have the classes assigned for the leaf nodes.</p></li>
<li><p>Goal: estimate <em>the classification error rate</em> for this tree.</p></li>
<li><p>We use the <em>resubstitution estimate</em> <span class="math inline">\(r(t)\)</span> for the probability of misclassification, given that a case falls into node <span class="math inline">\(t\)</span>. This is:</p></li>
</ul>
<p><span class="math display">\[
r(t)=1-\max _{j} p(j \mid t)=1-p(\kappa(t) \mid t)
\]</span></p>
</section>
<section id="tb-2.3.-estimating-the-error-rate-2" class="level2">
<h2 class="anchored" data-anchor-id="tb-2.3.-estimating-the-error-rate-2">TB 2.3. Estimating the error rate (2)</h2>
<ul>
<li><p>Denote <span class="math inline">\(R(t)=r(t) p(t)\)</span>, that is the miscclassification error rate weighted by the probability of the node.</p></li>
<li><p>The resubstitution estimation for the overall misclassification rate <span class="math inline">\(R(T)\)</span> of the tree classifier <span class="math inline">\(T\)</span> is: <span class="math display">\[
R(T)=\sum_{t \in \tilde{T}} R(t)
\]</span></p></li>
<li><p>Notice that this estimate is based on training data and may underestimate the true error!</p></li>
</ul>
</section>
<section id="example-2-individual-prediction" class="level2">
<h2 class="anchored" data-anchor-id="example-2-individual-prediction">Example 2: Individual prediction</h2>
<p>Consider individuals 521 and 562</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>(aSample<span class="ot">&lt;-</span> PimaIndiansDiabetes2[<span class="fu">c</span>(<span class="dv">521</span>,<span class="dv">562</span>),])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    pregnant glucose pressure triceps insulin mass pedigree age diabetes
521        2      68       70      32      66 25.0    0.187  25      neg
562        0     198       66      32     274 41.3    0.502  28      pos</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model1, aSample, <span class="st">"class"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>521 562 
neg pos 
Levels: neg pos</code></pre>
</div>
</div>
<ul>
<li><p>If we follow individuals 521 and 562 along the tree, we reach the same prediction.</p></li>
<li><p>The tree provides not only a classification but also an explanation.</p></li>
</ul>
</section>
<section id="example-2-how-accurate-is-the-model" class="level2">
<h2 class="anchored" data-anchor-id="example-2-how-accurate-is-the-model">Example 2: How accurate is the model?</h2>
<ul>
<li>It is straightforward to obtain a simple performance measure.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>predicted.classes<span class="ot">&lt;-</span> <span class="fu">predict</span>(model1, PimaIndiansDiabetes2, <span class="st">"class"</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(predicted.classes <span class="sc">==</span> PimaIndiansDiabetes2<span class="sc">$</span>diabetes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.8294271</code></pre>
</div>
</div>
</section>
<section id="example-2-is-the-tree-optimal" class="level2">
<h2 class="anchored" data-anchor-id="example-2-is-the-tree-optimal">Example 2: Is the Tree optimal?</h2>
<ul>
<li><p>The question becomes harder when we go back and ask if <em>we obtained the best possible tree</em>.</p></li>
<li><p>In order to answer this question we must study tree construction in more detail.</p></li>
</ul>
</section>
</section>
<section id="obtaining-best-trees" class="level1">
<h1>Obtaining best trees</h1>
<section id="tb-3.-controlling-tree-growth" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.-controlling-tree-growth">TB 3. Controlling tree growth</h2>
<p>Trees obtained by looking for optimal splits tend to overfit:</p>
<ul>
<li>good for the data in the tree, but</li>
<li>bad for generalization: tend to fail more in predictions.</li>
</ul>
<p>Assuming we wish to control tree growth there are distinct possible approaches:</p>
<ul>
<li>Stop early (<em>pre-pruning</em>)</li>
<li>Grow fully and prune later (<em>post-pruning</em>)</li>
</ul>
</section>
<section id="tb-3.1-optimizing-the-tree" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.1-optimizing-the-tree">TB 3.1 Optimizing the Tree</h2>
<ul>
<li><p>Stopping early may prevent overfitting, but can miss important structure.</p></li>
<li><p>In order to reduce complexity and overfitting, while keeping the tree as good as possible, tree <em>pruning</em> may be applied.</p></li>
<li><p>Pruning works <em>removing branches that are unlikely to improve the accuracy</em> of the model on new data.</p></li>
</ul>
<p>CART follows the second approach</p>
</section>
<section id="tb-3.2-cart-strategy-for-pruning" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.2-cart-strategy-for-pruning">TB 3.2 CART strategy for pruning</h2>
<p>CART uses the followin strategy to build optimal trees</p>
<ol type="1">
<li>Grow a large tree (overfit)</li>
<li>Prune it using a penalty</li>
<li>Select optimal tree size</li>
</ol>
<p>This is known as <em>Post-pruning</em> approach.</p>
</section>
<section id="tb-3.3-pruning-methods" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.3-pruning-methods">TB 3.3 Pruning methods</h2>
<ul>
<li><p>There are different pruning methods, but the most common one is to use the <em>cost-complexity pruning</em> algorithm, also known as the <em>weakest link pruning</em>.</p></li>
<li><p>The algorithm works by adding a penalty term to the misclassification rate of the terminal nodes:</p></li>
</ul>
<p><span class="math display">\[
R_\alpha(T) =R(T)+\alpha|T|
\]</span></p>
<ul>
<li><span class="math inline">\(\alpha\)</span> is the hyper-parameter that controls the trade-off between tree complexity and accuracy.</li>
</ul>
</section>
<section id="tb-3.3-cost-complexity-pruning" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.3-cost-complexity-pruning">TB 3.3 Cost-complexity pruning</h2>
<ul>
<li><p>First, grow a large tree that overfits the data</p></li>
<li><p>Then, generate a sequence of subtrees by pruning: for increasing values of <span class="math inline">\(\alpha\)</span>, smaller trees are obtained</p></li>
<li><p>Each subtree balances:</p>
<ul>
<li>fit to the data</li>
<li>tree complexity</li>
</ul></li>
<li><p>Finally, use cross-validation to select the optimal <span class="math inline">\(\alpha\)</span></p></li>
</ul>
<p><span class="math inline">\(\rightarrow\)</span> This determines the final tree size</p>
</section>
<section id="tb-3.4-cv-to-select-alpha" class="level2">
<h2 class="anchored" data-anchor-id="tb-3.4-cv-to-select-alpha">TB 3.4 CV to Select <span class="math inline">\(\alpha\)</span></h2>
<ul>
<li><p>Each sub-tree can by evaluated with cross-validation as follows:</p>
<ul>
<li>Split the data into K folds</li>
<li>Compute prediction error for each <span class="math inline">\(\alpha\)</span>, on validation folds</li>
<li>Average the error across folds</li>
</ul></li>
<li><p>Select the value of <span class="math inline">\(\alpha\)</span> with lowest validation error.</p></li>
</ul>
</section>
<section id="ex.-3-optimizing-the-tree-1" class="level2">
<h2 class="anchored" data-anchor-id="ex.-3-optimizing-the-tree-1">Ex. 3 Optimizing the tree (1)</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co">#printcp(model1)</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">round</span>(model1<span class="sc">$</span>cptable, <span class="dv">6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        CP nsplit rel error   xerror     xstd
1 0.242537      0  1.000000 1.000000 0.049288
2 0.100746      1  0.757463 0.832090 0.046939
3 0.011816      2  0.656716 0.779851 0.046022
4 0.011194     10  0.555970 0.757463 0.045599
5 0.010000     16  0.488806 0.757463 0.045599</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotcp</span>(model1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="ex-3.-building-the-optimal-tree" class="level2">
<h2 class="anchored" data-anchor-id="ex-3.-building-the-optimal-tree">Ex 3. Building the optimal tree</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>cp_opt <span class="ot">&lt;-</span> model1<span class="sc">$</span>cptable[<span class="fu">which.min</span>(model1<span class="sc">$</span>cptable[, <span class="st">"xerror"</span>]), <span class="st">"CP"</span>]</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>cp_opt</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.01119403</code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>model_pruned <span class="ot">&lt;-</span> <span class="fu">prune</span>(model1, <span class="at">cp =</span> cp_opt)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>rpart.plot<span class="sc">::</span><span class="fu">rpart.plot</span>(model_pruned)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="regression-trees" class="level1">
<h1>Regression Trees</h1>
<section id="regression-modelling-with-trees" class="level2">
<h2 class="anchored" data-anchor-id="regression-modelling-with-trees">Regression modelling with trees</h2>
<ul>
<li><p>When the response variable is numeric, decision trees are <em>regression trees</em>.</p></li>
<li><p>Option of choice for distinct reasons</p>
<ul>
<li>The relation between response and potential explanatory variables is not linear.</li>
<li>Perform automatic variable selection.</li>
<li>Easy to interpret, visualize, explain.</li>
<li>Robust to outliers and can handle missing data</li>
</ul></li>
</ul>
</section>
<section id="classification-vs-regression-trees" class="level2">
<h2 class="anchored" data-anchor-id="classification-vs-regression-trees">Classification vs Regression Trees</h2>
<div class="font50">
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 37%">
<col style="width: 37%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Aspect</strong></th>
<th style="text-align: left;"><strong>Regression Trees</strong></th>
<th style="text-align: left;"><strong>Classification Trees</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Outcome var. type</td>
<td style="text-align: left;">Continuous</td>
<td style="text-align: left;">Categorical</td>
</tr>
<tr class="even">
<td style="text-align: left;">Goal</td>
<td style="text-align: left;">To predict a numerical value</td>
<td style="text-align: left;">To predict a class label</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Splitting criteria</td>
<td style="text-align: left;">Mean Squared Error, Mean Abs. Error</td>
<td style="text-align: left;">Gini Impurity, Entropy, etc.</td>
</tr>
<tr class="even">
<td style="text-align: left;">Leaf node prediction</td>
<td style="text-align: left;">Mean or median of the target variable in that region</td>
<td style="text-align: left;">Mode or majority class of the target variable …</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Examples of use cases</td>
<td style="text-align: left;">Predicting housing prices, predicting stock prices</td>
<td style="text-align: left;">Predicting customer churn, predicting high/low risk in diease</td>
</tr>
<tr class="even">
<td style="text-align: left;">Evaluation metric</td>
<td style="text-align: left;">Mean Squared Error, Mean Absolute Error, R-square</td>
<td style="text-align: left;">Accuracy, Precision, Recall, F1-score, etc.</td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="regression-tree-example" class="level2">
<h2 class="anchored" data-anchor-id="regression-tree-example">Regression tree example</h2>
<ul>
<li>The <code>airquality</code> dataset from the <code>datasets</code> package contains daily air quality measurements in New York from May through September of 1973 (153 days).</li>
<li>The main variables include:
<ul>
<li>Ozone: the mean ozone (in parts per billion) …</li>
<li>Solar.R: the solar radiation (in Langleys) …</li>
<li>Wind: the average wind speed (in mph) …</li>
<li>Temp: the maximum daily temperature (ºF) …</li>
</ul></li>
<li>Main goal : Predict ozone concentration.</li>
</ul>
</section>
<section id="non-linear-relationships" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="non-linear-relationships">Non linear relationships!</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>aq <span class="ot">&lt;-</span> datasets<span class="sc">::</span>airquality</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>color <span class="ot">&lt;-</span> <span class="fu">adjustcolor</span>(<span class="st">"forestgreen"</span>, <span class="at">alpha.f =</span> <span class="fl">0.5</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>ps <span class="ot">&lt;-</span> <span class="cf">function</span>(x, y, ...) {  <span class="co"># custom panel function</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">panel.smooth</span>(x, y, <span class="at">col =</span> color, <span class="at">col.smooth =</span> <span class="st">"black"</span>, <span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a><span class="fu">pairs</span>(aq, <span class="at">cex =</span> <span class="fl">0.7</span>, <span class="at">upper.panel =</span> ps, <span class="at">col =</span> color)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="building-the-tree-1-splitting" class="level2">
<h2 class="anchored" data-anchor-id="building-the-tree-1-splitting">Building the tree (1): Splitting</h2>
<div class="font80">
<ul>
<li>Consider:
<ul>
<li>all predictors <span class="math inline">\(X_1, \dots, X_n\)</span>, and</li>
<li>all values of cutpoint <span class="math inline">\(s\)</span> for each predictor and</li>
</ul></li>
<li>For each predictor find boxes <span class="math inline">\(R_1, \ldots, R_J\)</span> that minimize the RSS, given by:</li>
</ul>
<p><span class="math display">\[
\sum_{j=1}^J \sum_{i \in R_j}\left(y_i-\hat{y}_{R_j}\right)^2
\]</span></p>
<p>where <span class="math inline">\(\hat{y}_{R_j}\)</span> is the mean response for the training observations within the <span class="math inline">\(j\)</span> th box.</p>
</div>
</section>
<section id="building-the-tree-2-splitting" class="level2">
<h2 class="anchored" data-anchor-id="building-the-tree-2-splitting">Building the tree (2): Splitting</h2>
<div class="font80">
<ul>
<li>To do this, define the pair of half-planes</li>
</ul>
<p><span class="math display">\[
R_1(j, s)=\left\{X \mid X_j&lt;s\right\} \text { and } R_2(j, s)=\left\{X \mid X_j \geq s\right\}
\]</span></p>
<p>and seek the value of <span class="math inline">\(j\)</span> and <span class="math inline">\(s\)</span> that minimize the equation:</p>
<p><span class="math display">\[
\sum_{i: x_i \in R_1(j, s)}\left(y_i-\hat{y}_{R_1}\right)^2+\sum_{i: x_i \in R_2(j, s)}\left(y_i-\hat{y}_{R_2}\right)^2.
\]</span></p>
</div>
</section>
<section id="building-the-tree-3-prediction" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="building-the-tree-3-prediction">Building the tree (3): Prediction</h2>
<div class="columns">
<div class="column" style="width:40%;">
<ul>
<li><p>Once the regions have been created we predict the response using the mean of the trainig observations <em>in the region to which that observation belongs</em>.</p></li>
<li><p>In the example, for an observation belonging to the shaded region, the prediction would be:</p></li>
</ul>
<p><span class="math display">\[
\hat{y} =\frac{1}{4}(y_2+y_3+y_5+y_9)
\]</span></p>
</div><div class="column" style="width:60%;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">"images/RegressionTree-Prediction1.png"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/RegressionTree-Prediction1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:100.0%"></p>
</figure>
</div>
</div>
</div>
</div>
</div>
</section>
<section id="example-a-regression-tree" class="level2">
<h2 class="anchored" data-anchor-id="example-a-regression-tree">Example: A regression tree</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(aq), <span class="at">size =</span> <span class="fu">nrow</span>(aq)<span class="sc">*</span><span class="fl">0.7</span>)</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>aq_train <span class="ot">&lt;-</span> aq[train,]</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>aq_test  <span class="ot">&lt;-</span> aq[<span class="sc">-</span>train,]</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>aq_regresion <span class="ot">&lt;-</span> tree<span class="sc">::</span><span class="fu">tree</span>(<span class="at">formula =</span> Ozone <span class="sc">~</span> ., </span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">data =</span> aq_train, <span class="at">split =</span> <span class="st">"deviance"</span>)</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aq_regresion)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
tree::tree(formula = Ozone ~ ., data = aq_train, split = "deviance")
Variables actually used in tree construction:
[1] "Temp"    "Wind"    "Solar.R" "Day"    
Number of terminal nodes:  8 
Residual mean deviance:  285.6 = 21420 / 75 
Distribution of residuals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-58.2000  -7.9710  -0.4545   0.0000   5.5290  81.8000 </code></pre>
</div>
</div>
</section>
<section id="example-plot-the-tree" class="level2">
<h2 class="anchored" data-anchor-id="example-plot-the-tree">Example: Plot the tree</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mar =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="at">x =</span> aq_regresion, <span class="at">type =</span> <span class="st">"proportional"</span>)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> aq_regresion, <span class="at">splits =</span> <span class="cn">TRUE</span>, <span class="at">pretty =</span> <span class="dv">0</span>, <span class="at">cex =</span> <span class="fl">0.8</span>, <span class="at">col =</span> <span class="st">"firebrick"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="C2.1-DecisionTrees-Slides-body_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="error-estimation-and-optimization-for-regression-trees" class="level1">
<h1>Error estimation and optimization for regression trees</h1>
<section id="prunning-the-tree-1" class="level2">
<h2 class="anchored" data-anchor-id="prunning-the-tree-1">Prunning the tree (1)</h2>
<ul>
<li>As before, <em>cost-complexity prunning</em> can be applied</li>
<li>We consider a sequence of trees indexed by a nonnegative tuning parameter <span class="math inline">\(\alpha\)</span>.</li>
<li>For each value of <span class="math inline">\(\alpha\)</span> there corresponds a subtree <span class="math inline">\(T \subset T_0\)</span> such that:</li>
</ul>
<div class="font80">
<p><span class="math display">\[
\sum_{m=1}^{|T|} \sum_{y_i \in R_m}
\left(y_i -\hat{y}_{R_m}\right)^2+
\alpha|T|\quad (*)
\label{prunning}
\]</span></p>
</div>
<p>is as small as possible.</p>
</section>
<section id="tuning-parameter-alpha" class="level2">
<h2 class="anchored" data-anchor-id="tuning-parameter-alpha">Tuning parameter <span class="math inline">\(\alpha\)</span></h2>
<ul>
<li><span class="math inline">\(\alpha\)</span> controls a trade-off between the subtree’s complexity and its fit to the training data.</li>
<li>When <span class="math inline">\(\alpha=0\)</span>, then the subtree <span class="math inline">\(T\)</span> will simply equal <span class="math inline">\(T_0\)</span>.</li>
<li>As <span class="math inline">\(\alpha\)</span> increases, there is a price to pay for having a tree with many terminal nodes, and so (*) will tend to be minimized for a smaller subtree.</li>
<li>Equation (*1) is reminiscent of the lasso.</li>
<li><span class="math inline">\(\alpha\)</span> can be chosen by cross-validation .</li>
</ul>
</section>
<section id="optimizing-the-tree-alpha" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="optimizing-the-tree-alpha">Optimizing the tree (<span class="math inline">\(\alpha\)</span>)</h2>
<ol type="1">
<li><p>Use recursive binary splitting to grow a large tree on the training data, stopping only when each terminal node has fewer than some minimum number of observations.</p></li>
<li><p>Apply cost complexity pruning to the large tree in order to obtain a sequence of best subtrees, as a function of <span class="math inline">\(\alpha\)</span>.</p></li>
<li><p>Use K-fold cross-validation to choose <span class="math inline">\(\alpha\)</span>. That is, divide the training observations into <span class="math inline">\(K\)</span> folds. For each <span class="math inline">\(k=1, \ldots, K\)</span> :</p>
<ol type="1">
<li>Repeat Steps 1 and 2 on all but the <span class="math inline">\(k\)</span> th fold of the training data.</li>
<li>Evaluate the mean squared prediction error on the data in the left-out <span class="math inline">\(k\)</span> th fold, as a function of <span class="math inline">\(\alpha\)</span>.</li>
</ol></li>
</ol>
<p>Average the results for each value of <span class="math inline">\(\alpha\)</span>. Pick <span class="math inline">\(\alpha\)</span> to minimize the average error.</p>
<ol start="4" type="1">
<li>Return the subtree from Step 2 that corresponds to the chosen value of <span class="math inline">\(\alpha\)</span>.</li>
</ol>
</section>
<section id="example-prune-the-tree" class="level2">
<h2 class="anchored" data-anchor-id="example-prune-the-tree">Example: Prune the tree</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>cv_aq <span class="ot">&lt;-</span> tree<span class="sc">::</span><span class="fu">cv.tree</span>(aq_regresion, <span class="at">K =</span> <span class="dv">5</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>optimal_size <span class="ot">&lt;-</span>  <span class="fu">rev</span>(cv_aq<span class="sc">$</span>size)[<span class="fu">which.min</span>(<span class="fu">rev</span>(cv_aq<span class="sc">$</span>dev))]</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>aq_final_tree <span class="ot">&lt;-</span> tree<span class="sc">::</span><span class="fu">prune.tree</span>(</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>                 <span class="at">tree =</span> aq_regresion,</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>                 <span class="at">best =</span> optimal_size</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a>               )</span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(aq_final_tree)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Regression tree:
tree::tree(formula = Ozone ~ ., data = aq_train, split = "deviance")
Variables actually used in tree construction:
[1] "Temp"    "Wind"    "Solar.R" "Day"    
Number of terminal nodes:  8 
Residual mean deviance:  285.6 = 21420 / 75 
Distribution of residuals:
    Min.  1st Qu.   Median     Mean  3rd Qu.     Max. 
-58.2000  -7.9710  -0.4545   0.0000   5.5290  81.8000 </code></pre>
</div>
</div>
<p>In this example pruning does not improve the tree.</p>
</section>
</section>
<section id="advantages-and-disadvantages-of-trees" class="level1">
<h1>Advantages and disadvantages of trees</h1>
<section id="trees-have-many-advantages" class="level2">
<h2 class="anchored" data-anchor-id="trees-have-many-advantages">Trees have many advantages</h2>
<ul>
<li><p>Trees are very easy to explain to people.</p></li>
<li><p>Decision trees may be seen as good mirrors of human decision-making.</p></li>
<li><p>Trees can be displayed graphically, and are easily interpreted even by a non-expert.</p></li>
<li><p>Trees can easily handle qualitative predictors without the need to create dummy variables.</p></li>
</ul>
</section>
<section id="but-they-come-at-a-price" class="level2">
<h2 class="anchored" data-anchor-id="but-they-come-at-a-price">But they come at a price</h2>
<ul>
<li><p>Trees generally do not have the same level of predictive accuracy as sorne of the other regression and classification approaches.</p></li>
<li><p>Additionally, trees can be very non-robust: a small change in the data can cause a large change in the final estimated tree.</p></li>
</ul>
</section>
</section>
<section id="references-and-resources" class="level1">
<h1>References and Resources</h1>
<section id="references" class="level2 smaller">
<h2 class="smaller anchored" data-anchor-id="references">References</h2>
<ul>
<li><p><a href="https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/decisionForests_MSR_TR_2011_114.pdf">A. Criminisi, J. Shotton and E. Konukoglu (2011) Decision Forests for Classifcation, Regression … Microsoft Research technical report TR-2011-114</a></p></li>
<li><p>Efron, B., Hastie T. (2016) Computer Age Statistical Inference. Cambridge University Press. <a href="https://hastie.su.domains/CASI/index.html">Web site</a></p></li>
<li><p>Hastie, T., Tibshirani, R., &amp; Friedman, J. (2009). The elements of statistical learning: Data mining, inference, and prediction. Springer.</p></li>
<li><p>James, G., Witten, D., Hastie, T., &amp; Tibshirani, R. (2013). An introduction to statistical learning (Vol. 112). Springer. <a href="https://www.statlearning.com/">Web site</a></p></li>
</ul>
</section>
<section id="complementary-references" class="level2">
<h2 class="anchored" data-anchor-id="complementary-references">Complementary references</h2>
<ul>
<li><p>Breiman, L., Friedman, J., Stone, C. J., &amp; Olshen, R. A. (1984). Classification and regression trees. CRC press.</p></li>
<li><p>Brandon M. Greenwell (202) Tree-Based Methods for Statistical Learning in R. 1st Edition. Chapman and Hall/CRC DOI: https://doi.org/10.1201/9781003089032</p></li>
<li><p>Genuer R., Poggi, J.M. (2020) Random Forests with R. Springer ed. (UseR!)</p></li>
</ul>
</section>
<section id="resources" class="level2">
<h2 class="anchored" data-anchor-id="resources">Resources</h2>
<ul>
<li><p><a href="https://online.stat.psu.edu/stat508/">Applied Data Mining and Statistical Learning (Penn Statte-University)</a></p></li>
<li><p><a href="https://daviddalpiaz.github.io/r4sl/">R for statistical learning</a></p></li>
<li><p><a href="http://www.sthda.com/english/articles/35-statistical-machine-learning-essentials/141-cart-model-decision-tree-essentials/#example-of-data-set">CART Model: Decision Tree Essentials</a></p></li>
<li><p><a href="https://cran.r-project.org/web/packages/rpart/vignettes/longintro.pdf">An Introduction to Recursive Partitioning Using the RPART Routines</a></p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>