name: Render and Deploy Quarto Site

on:
  push:
    branches:
      - main  # Change if using another branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache Quarto installation
      - name: Cache Quarto
        uses: actions/cache@v3
        with:
          path: /opt/quarto
          key: quarto-v1

      # Install Quarto only if not cached
      - name: Install Quarto  # <-- Fixed indentation
        run: |
          if ! command -v quarto &> /dev/null; then
            wget https://quarto.org/download/latest/quarto-linux-amd64.deb
            sudo dpkg -i quarto-linux-amd64.deb
          fi

      # Cache TinyTeX installation
      - name: Cache TinyTeX
        uses: actions/cache@v3
        with:
          path: ~/.TinyTeX
          key: tinytex-v1

      # Install TinyTeX only if not cached
      - name: Install TinyTeX
        run: |
          if [ ! -d ~/.TinyTeX ]; then
            quarto install tinytex
          fi
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      # Render Quarto website
      - name: Render site
        run: quarto render

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
